### ISSUE TITLE
Compile for Mac

### ISSUE THREAD

**Issue by patrick-brielmayer** [svenpaulsen/ts3client-notification-plugin#1]
Hey there, 
I forked the repo and compiled it with qmake;make.
After putting the dylib file to the plugins directory in "/Users/USER/Library/Application Support/TeamSpeak 3/plugins", Teamspeak failed to initialize the plugin: "Plugin reported initialization failure. Please contact the plugin author". 
What did I do wrong?
Cheers m8

**Comment by svenpaulsen** [comment]
On macOS, you'll need to adjust the locations of the linked Qt libraries. First, check the dependencies of the plugin with **otool**:

```bash
otool -L plugin.dylib
```

After that, use install_name_tool to change the path of the linked Qt libraries:

```bash
install_name_tool -change /old/path/to/QtLib.dylib /new/path/to/QtLib.dylib plugin.dylib
```

Feel free to download my latest build from the releases page and use otool to see what the dependencies should look like:

https://github.com/svenpaulsen/ts3client-notification-plugin/releases
