### ISSUE TITLE
TS3 crash on connect when nicknames are too long

### ISSUE THREAD

**Issue by tiapfy** [svenpaulsen/ts3client-notification-plugin#4]
If somebody in the server you're connecting to has a nickname longer than a certain number of character (I think it's 32 characters if we consider the spaces as 2 chars, as TS3 does for the chat). I've experienced this more than once and to fix this I disable the plugin, connect to the server and then reenable it.

**Comment by svenpaulsen** [comment]
This should be resolved with the current master. I was just being stupid... so let's just forget that this bug ever existed. 😜
